apiVersion: v1
kind: ReplicationController
metadata:
  name: web
  labels:
    name: web
    app: demo
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
        - name: web
          image: xiaopeng163/docker-flask-demo:1.0
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP
